
project_id = "qqcmhbliavkxsewlphbk"

[db_config]
migrations_path = "supabase/migrations"

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enable_signup = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
